version: '3.8'
services:
  caddy:
    image: caddy:latest
    container_name: caddy
    hostname: caddy
    restart: unless-stopped
    volumes:
      - /home/html:/usr/share/caddy
      - /home:/etc/caddy
    ports:
      - "80:80"
      - "443:443"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    hostname: server
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    ports:
      - "9000:9000"
    volumes:
      - /home/data/nginx:/common/nginx
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /home/data/mysql/data:/var/lib/mysql
      - /home/data/mysql/init:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: qq81880234
      MYSQL_DATABASE: gochat
    ports:
      - "3306:3306"
  redis:
    image: redis:7.0.15
    container_name: redis
    hostname: redis
    restart: unless-stopped
    volumes:
      - /home/data/redis/conf:/usr/local/etc/redis
      - /home/data/redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    restart: unless-stopped
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - /home/data/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"


