mysql:
  driverName: mysql
  host: 47.113.104.184
  port: 3306
  database: gochat
  username: root
  password: qq81880234
  charset: utf8mb4

redis:
  addr: 47.113.104.184:6379
  password: 123123
  DB: 0
  poolSize: 30
  minIdleConn: 30

rabbit:
  driverName : amqp
  userName : guest
  password: guest
  address: 47.113.104.184:5672

oss:
  Endpoint: "oss-cn-hangzhou.aliyuncs.com"
  AccessKeyId: "LTAI5tNCXPJwS3MstKoKgixh"
  AccessKeySecret: "YhHE8OyCMsqfjwOnxQ1oO7paYlDjVHX"
  Bucket : "gochat"

timeout:
  DelayHeartbeat: 3   #延迟心跳时间  单位秒
  HeartbeatHz: 30   #每隔多少秒心跳时间
  HeartbeatMaxTime: 30000  #最大心跳时间  ，超过此就下线
  RedisOnlineTime: 7  #缓存的在线用户时长   单位H

port:
  server: ":9000"
  udp: 3001

etcd:
  address: 127.0.0.1:9000